version: '3'

services:
  postgres-service-container:
    image: postgres:9.4-alpine
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PWD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - netmsbackend
  java-microservicio-01:
    image: test01:v01
    environment:
      - PG_USER
      - PG_PWD
      - PG_DB
      - PG_SERVER=postgres-service-container
      - PG_SERVER_PORT=5432
    ports:
      - "3081"
    depends_on:
      - postgres-service-container
    networks:
      - netlbfront
      - netmsbackend
  java-microservicio-02:
    image: test01:v01
    environment:
      - PG_USER
      - PG_PWD
      - PG_DB
      - PG_SERVER=postgres-service-container
      - PG_SERVER_PORT=5432
    ports:
      - "3081"
    depends_on:
      - postgres-service-container
    networks:
      - netlbfront
      - netmsbackend
  load-balancer:
    build:
      context: $PWD/nginx
    restart: always
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - "8089:80"
    depends_on:
      - java-microservicio-01
      - java-microservicio-02
    networks:
      - netlbfront
  web-ui:
    build:
      context: $PWD/frontend-ui
    restart: always
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - "8090:80"
networks:
    netlbfront:
    netmsbackend:
