version: '3'

services:
  postgres-service-container:
    image: postgres:9.4-alpine
    restart: always
    environment:
      POSTGRES_USER: pguser01
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: pgdatabase
    ports:
      - "5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - netmsbackend
  java-microservicio-01:
    image: test01:v01
    ports:
      - "3081"
    depends_on:
      - postgres-service-container
    networks:
      - netlbfront
      - netmsbackend
  load-balancer:
    build:
      context: $PWD/nginx
    restart: always
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - "8089:80"
    depends_on:
      - java-microservicio-01
    networks:
      - netlbfront
networks:
    netlbfront:
    netmsbackend: